app.title=QLRP - Quản lý rạp chiếu phim
db.url=jdbc:mysql://localhost:3306/qlrp?useSSL=false&allowPublicKeyRetrieval=true&connectionTimeZone=Asia/Ho_Chi_Minh&forceConnectionTimeZoneToSession=true&characterEncoding=UTF-8
db.username=qlrp_user
db.password=qlrp_pass
app.charset=UTF-8
